<?php
/**
 * @category   Webkul
 * @package    Webkul_Events
 * @author     webkul@czargroup.net
 * @copyright  This file was generated by using Module Creator provided by <developer@czargroup.net>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Webkul\Second\Model\ResourceModel\Events;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'entity_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'Webkul\Second\Model\Events',
            'Webkul\Second\Model\ResourceModel\Events'
        );
    }
}
